//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckHash.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckHash.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Assistance.
        /// </summary>
        public static string About_AI {
            get {
                return ResourceManager.GetString("About_AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software was developed with assistance from AI (Gemini 3 Pro and Grok 4.1)..
        /// </summary>
        public static string About_AIContent {
            get {
                return ResourceManager.GetString("About_AIContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string About_Author {
            get {
                return ResourceManager.GetString("About_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A powerful tool for generating, verifying, and compressing file hashes. Or so I think :).
        /// </summary>
        public static string About_Desc {
            get {
                return ResourceManager.GetString("About_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released under the MIT License..
        /// </summary>
        public static string About_License {
            get {
                return ResourceManager.GetString("About_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        public static string About_Software {
            get {
                return ResourceManager.GetString("About_Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        public static string About_Tech {
            get {
                return ResourceManager.GetString("About_Tech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built with C# and .NET 10.0.102..
        /// </summary>
        public static string About_TechContent {
            get {
                return ResourceManager.GetString("About_TechContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-party Libraries.
        /// </summary>
        public static string About_ThirdParty {
            get {
                return ResourceManager.GetString("About_ThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash Tool.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Btn_Accept {
            get {
                return ResourceManager.GetString("Btn_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files....
        /// </summary>
        public static string Btn_AddFiles {
            get {
                return ResourceManager.GetString("Btn_AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder....
        /// </summary>
        public static string Btn_AddFolder {
            get {
                return ResourceManager.GetString("Btn_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPUTE ALL.
        /// </summary>
        public static string Btn_CalcAll {
            get {
                return ResourceManager.GetString("Btn_CalcAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFY ALL.
        /// </summary>
        public static string Btn_CheckAll {
            get {
                return ResourceManager.GetString("Btn_CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Now.
        /// </summary>
        public static string Btn_CheckNow {
            get {
                return ResourceManager.GetString("Btn_CheckNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear List.
        /// </summary>
        public static string Btn_Clear {
            get {
                return ResourceManager.GetString("Btn_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Failed.
        /// </summary>
        public static string Btn_ClearFailed {
            get {
                return ResourceManager.GetString("Btn_ClearFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress (.Zip).
        /// </summary>
        public static string Btn_Compress {
            get {
                return ResourceManager.GetString("Btn_Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Btn_Decline {
            get {
                return ResourceManager.GetString("Btn_Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Btn_Install {
            get {
                return ResourceManager.GetString("Btn_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Btn_No {
            get {
                return ResourceManager.GetString("Btn_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Btn_OK {
            get {
                return ResourceManager.GetString("Btn_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Btn_Yes {
            get {
                return ResourceManager.GetString("Btn_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Edition.
        /// </summary>
        public static string Channel_Dev {
            get {
                return ResourceManager.GetString("Channel_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stable.
        /// </summary>
        public static string Channel_Stable {
            get {
                return ResourceManager.GetString("Channel_Stable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature allows you to install a specific version if the new one has issues..
        /// </summary>
        public static string Desc_Fallback {
            get {
                return ResourceManager.GetString("Desc_Fallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BETA.
        /// </summary>
        public static string Dev_Beta {
            get {
                return ResourceManager.GetString("Dev_Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Console.
        /// </summary>
        public static string Dev_Clear {
            get {
                return ResourceManager.GetString("Dev_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Console.
        /// </summary>
        public static string Dev_Console {
            get {
                return ResourceManager.GetString("Dev_Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy All.
        /// </summary>
        public static string Dev_Copy {
            get {
                return ResourceManager.GetString("Dev_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Save.
        /// </summary>
        public static string Dev_NoSave {
            get {
                return ResourceManager.GetString("Dev_NoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log Folder.
        /// </summary>
        public static string Dev_OpenFolder {
            get {
                return ResourceManager.GetString("Dev_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string Dev_Paused {
            get {
                return ResourceManager.GetString("Dev_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        public static string Dev_Recording {
            get {
                return ResourceManager.GetString("Dev_Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to File.
        /// </summary>
        public static string Dev_SaveToFile {
            get {
                return ResourceManager.GetString("Dev_SaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause real-time logging..
        /// </summary>
        public static string Dev_ToolTip_Pause {
            get {
                return ResourceManager.GetString("Dev_ToolTip_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save debug log to disk..
        /// </summary>
        public static string Dev_ToolTip_Save {
            get {
                return ResourceManager.GetString("Dev_ToolTip_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Archive.
        /// </summary>
        public static string Dialog_FileType_Zip {
            get {
                return ResourceManager.GetString("Dialog_FileType_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Hash File.
        /// </summary>
        public static string Dialog_SaveHash {
            get {
                return ResourceManager.GetString("Dialog_SaveHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Compressed File.
        /// </summary>
        public static string Dialog_SaveZip {
            get {
                return ResourceManager.GetString("Dialog_SaveZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Files (Original or .hash File).
        /// </summary>
        public static string Dialog_SelectCheckFiles {
            get {
                return ResourceManager.GetString("Dialog_SelectCheckFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Files to Hash.
        /// </summary>
        public static string Dialog_SelectFiles {
            get {
                return ResourceManager.GetString("Dialog_SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder to Scan.
        /// </summary>
        public static string Dialog_SelectFolder {
            get {
                return ResourceManager.GetString("Dialog_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select hash file for: {0}.
        /// </summary>
        public static string Dialog_SelectHashFile {
            get {
                return ResourceManager.GetString("Dialog_SelectHashFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files. Click &apos;Add Files&apos; to start..
        /// </summary>
        public static string EmptyState_DropFiles {
            get {
                return ResourceManager.GetString("EmptyState_DropFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub API rate limit exceeded. Please try again later..
        /// </summary>
        public static string Error_ApiLimit {
            get {
                return ResourceManager.GetString("Error_ApiLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client error (4xx). Please check the request..
        /// </summary>
        public static string Error_Client {
            get {
                return ResourceManager.GetString("Error_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network connection error. Please check your internet connection..
        /// </summary>
        public static string Error_Network {
            get {
                return ResourceManager.GetString("Error_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error (5xx). Please try again later..
        /// </summary>
        public static string Error_Server {
            get {
                return ResourceManager.GetString("Error_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced: Fallback to Older Version.
        /// </summary>
        public static string Header_Fallback {
            get {
                return ResourceManager.GetString("Header_Fallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Shift+A to Verify All, Ctrl+F to Add Files, Ctrl+Shift+H to Clear List..
        /// </summary>
        public static string Help_CheckHash {
            get {
                return ResourceManager.GetString("Help_CheckHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Shift+C to Compute All, Shift+Z to Compress, Ctrl+F to Add Files..
        /// </summary>
        public static string Help_CreateHash {
            get {
                return ResourceManager.GetString("Help_CreateHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release channel:.
        /// </summary>
        public static string Lbl_Channel {
            get {
                return ResourceManager.GetString("Lbl_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version: {0}.
        /// </summary>
        public static string Lbl_CurrentVersion {
            get {
                return ResourceManager.GetString("Lbl_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ {0} ({1:F2}%) | ❌ {2} ({3:F2}%) | ⛔ {4} ({5:F2}%).
        /// </summary>
        public static string Lbl_DetailedStats {
            get {
                return ResourceManager.GetString("Lbl_DetailedStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} ({2:F2}%).
        /// </summary>
        public static string Lbl_ProgressStats {
            get {
                return ResourceManager.GetString("Lbl_ProgressStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample:.
        /// </summary>
        public static string Lbl_Sample {
            get {
                return ResourceManager.GetString("Lbl_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read: {0}/s | Write: {1}/s.
        /// </summary>
        public static string Lbl_Speed {
            get {
                return ResourceManager.GetString("Lbl_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Lbl_Status_Ready {
            get {
                return ResourceManager.GetString("Lbl_Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total files: {0}.
        /// </summary>
        public static string Lbl_TotalFiles {
            get {
                return ResourceManager.GetString("Lbl_TotalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Hash.
        /// </summary>
        public static string Menu_Check {
            get {
                return ResourceManager.GetString("Menu_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Hash.
        /// </summary>
        public static string Menu_Create {
            get {
                return ResourceManager.GetString("Menu_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string Menu_Developer {
            get {
                return ResourceManager.GetString("Menu_Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Menu_Theme {
            get {
                return ResourceManager.GetString("Menu_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Menu_Update {
            get {
                return ResourceManager.GetString("Menu_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Mode.
        /// </summary>
        public static string Msg_AdminMode {
            get {
                return ResourceManager.GetString("Msg_AdminMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application for changes to take effect..
        /// </summary>
        public static string Msg_AdminRestart {
            get {
                return ResourceManager.GetString("Msg_AdminRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked {0} files.
        ///            ✅ Match: {1}
        ///            ❌ Mismatch/Error: {2}
        ///            ⛔ Cancelled: {3}
        ///        .
        /// </summary>
        public static string Msg_CheckResult {
            get {
                return ResourceManager.GetString("Msg_CheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0} items..
        /// </summary>
        public static string Msg_ClearedFailed {
            get {
                return ResourceManager.GetString("Msg_ClearedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Check.
        /// </summary>
        public static string Msg_ConfigCheck {
            get {
                return ResourceManager.GetString("Msg_ConfigCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration path copied..
        /// </summary>
        public static string Msg_ConfigCopied {
            get {
                return ResourceManager.GetString("Msg_ConfigCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File created successfully!.
        /// </summary>
        public static string Msg_ConfigCreated {
            get {
                return ResourceManager.GetString("Msg_ConfigCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File exists at:
        ///            {0}
        ///        .
        /// </summary>
        public static string Msg_ConfigExists {
            get {
                return ResourceManager.GetString("Msg_ConfigExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist!.
        /// </summary>
        public static string Msg_ConfigMissing {
            get {
                return ResourceManager.GetString("Msg_ConfigMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting will cancel all ongoing tasks. Are you sure?.
        /// </summary>
        public static string Msg_ConfirmExit_Content {
            get {
                return ResourceManager.GetString("Msg_ConfirmExit_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Exit.
        /// </summary>
        public static string Msg_ConfirmExit_Title {
            get {
                return ResourceManager.GetString("Msg_ConfirmExit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and agree. I accept full responsibility..
        /// </summary>
        public static string Msg_DisclaimerAgree {
            get {
                return ResourceManager.GetString("Msg_DisclaimerAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to switch to the Developer (Pre-release) update channel.
        ///
        ///            This version may contain bugs, be unstable, and could cause data loss.
        ///
        ///            I am not responsible for any issues arising from using this version.
        ///        .
        /// </summary>
        public static string Msg_DisclaimerContent {
            get {
                return ResourceManager.GetString("Msg_DisclaimerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ DEVELOPER VERSION WARNING.
        /// </summary>
        public static string Msg_DisclaimerTitle {
            get {
                return ResourceManager.GetString("Msg_DisclaimerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your drive is out of space. Please choose another location :).
        /// </summary>
        public static string Msg_DiskFull {
            get {
                return ResourceManager.GetString("Msg_DiskFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show this alert again.
        /// </summary>
        public static string Msg_DontShowAgain {
            get {
                return ResourceManager.GetString("Msg_DontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder is empty..
        /// </summary>
        public static string Msg_EmptyFolder {
            get {
                return ResourceManager.GetString("Msg_EmptyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining: {0}.
        /// </summary>
        public static string Msg_EstimatedTime {
            get {
                return ResourceManager.GetString("Msg_EstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} files. Skipped {1} files due to limit..
        /// </summary>
        public static string Msg_FileLimit {
            get {
                return ResourceManager.GetString("Msg_FileLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped {0} files exceeding limit ({1} {2}):
        ///            {3}
        ///        .
        /// </summary>
        public static string Msg_FileSizeLimitExceeded_Summary {
            get {
                return ResourceManager.GetString("Msg_FileSizeLimitExceeded_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only select up to {0} folders at a time..
        /// </summary>
        public static string Msg_FolderLimit {
            get {
                return ResourceManager.GetString("Msg_FolderLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure about that?.
        /// </summary>
        public static string Msg_LanguageChangeConfirmation {
            get {
                return ResourceManager.GetString("Msg_LanguageChangeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Change.
        /// </summary>
        public static string Msg_LanguageChangeTitle {
            get {
                return ResourceManager.GetString("Msg_LanguageChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pre-release version found. Keeping current version..
        /// </summary>
        public static string Msg_NoPreRelease {
            get {
                return ResourceManager.GetString("Msg_NoPreRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No newer updates found..
        /// </summary>
        public static string Msg_NoUpdate {
            get {
                return ResourceManager.GetString("Msg_NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open folder: {0}.
        /// </summary>
        public static string Msg_OpenFolderError {
            get {
                return ResourceManager.GetString("Msg_OpenFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-release version {0} is available.
        ///
        ///            {1}
        ///
        ///            This version may be unstable. Do you want to download?
        ///        .
        /// </summary>
        public static string Msg_PreReleaseWarning {
            get {
                return ResourceManager.GetString("Msg_PreReleaseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read this hash file..
        /// </summary>
        public static string Msg_ReadHashError {
            get {
                return ResourceManager.GetString("Msg_ReadHashError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing completed!
        ///            ✅ Success: {0}
        ///            ❌ Failed: {1}
        ///            ⛔ Cancelled: {2}
        ///        .
        /// </summary>
        public static string Msg_Result_Content {
            get {
                return ResourceManager.GetString("Msg_Result_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Msg_Result_Title {
            get {
                return ResourceManager.GetString("Msg_Result_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Language.
        /// </summary>
        public static string Msg_SystemLanguage {
            get {
                return ResourceManager.GetString("Msg_SystemLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning to &apos;Auto&apos; setting requires a restart to fully take effect. Do you want to continue?.
        /// </summary>
        public static string Msg_SystemLanguageWarning {
            get {
                return ResourceManager.GetString("Msg_SystemLanguageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task was stopped due to timeout..
        /// </summary>
        public static string Msg_TaskCancelled_Content {
            get {
                return ResourceManager.GetString("Msg_TaskCancelled_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Stopped.
        /// </summary>
        public static string Msg_TaskCancelled_Title {
            get {
                return ResourceManager.GetString("Msg_TaskCancelled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating....
        /// </summary>
        public static string Msg_TimeUnknown {
            get {
                return ResourceManager.GetString("Msg_TimeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}
        ///
        ///            Changes:
        ///            {1}
        ///
        ///            Click &apos;Update Now&apos; to download.
        ///        .
        /// </summary>
        public static string Msg_UpdateContent {
            get {
                return ResourceManager.GetString("Msg_UpdateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Update.
        /// </summary>
        public static string Msg_UpdateTitle {
            get {
                return ResourceManager.GetString("Msg_UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong file!.
        /// </summary>
        public static string Msg_WrongHashFile {
            get {
                return ResourceManager.GetString("Msg_WrongHashFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash file mismatch!
        ///
        ///            Original file: {0}
        ///            Selected file: {1}
        ///
        ///            Please select the correct accompanying hash file.
        ///        .
        /// </summary>
        public static string Msg_WrongHashFileContent {
            get {
                return ResourceManager.GetString("Msg_WrongHashFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires restart. Allows access to protected files..
        /// </summary>
        public static string Settings_AdminDesc {
            get {
                return ResourceManager.GetString("Settings_AdminDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as Administrator.
        /// </summary>
        public static string Settings_AdminMode {
            get {
                return ResourceManager.GetString("Settings_AdminMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Settings_Advanced {
            get {
                return ResourceManager.GetString("Settings_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-select optimal font for language.
        /// </summary>
        public static string Settings_AutoFont {
            get {
                return ResourceManager.GetString("Settings_AutoFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings are auto-saved to config.json.
        /// </summary>
        public static string Settings_AutoSave {
            get {
                return ResourceManager.GetString("Settings_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Quit &amp; Cancel All.
        /// </summary>
        public static string Settings_BtnForceQuit {
            get {
                return ResourceManager.GetString("Settings_BtnForceQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show full path and copy to clipboard..
        /// </summary>
        public static string Settings_ConfigDesc {
            get {
                return ResourceManager.GetString("Settings_ConfigDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration File Path.
        /// </summary>
        public static string Settings_ConfigPath {
            get {
                return ResourceManager.GetString("Settings_ConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Settings_Configuration {
            get {
                return ResourceManager.GetString("Settings_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Text Color.
        /// </summary>
        public static string Settings_CustomColor {
            get {
                return ResourceManager.GetString("Settings_CustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable advanced logging and debugging tools..
        /// </summary>
        public static string Settings_DeveloperDesc {
            get {
                return ResourceManager.GetString("Settings_DeveloperDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Mode.
        /// </summary>
        public static string Settings_DeveloperMode {
            get {
                return ResourceManager.GetString("Settings_DeveloperMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Action.
        /// </summary>
        public static string Settings_Emergency {
            get {
                return ResourceManager.GetString("Settings_Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force quit the app and cancel all tasks immediately..
        /// </summary>
        public static string Settings_EmergencyDesc {
            get {
                return ResourceManager.GetString("Settings_EmergencyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum size for files to process..
        /// </summary>
        public static string Settings_FileSizeDesc {
            get {
                return ResourceManager.GetString("Settings_FileSizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input File Size Limit.
        /// </summary>
        public static string Settings_FileSizeLimit {
            get {
                return ResourceManager.GetString("Settings_FileSizeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Processing Timeout.
        /// </summary>
        public static string Settings_FileTimeout {
            get {
                return ResourceManager.GetString("Settings_FileTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel if a single file takes too long..
        /// </summary>
        public static string Settings_FileTimeoutDesc {
            get {
                return ResourceManager.GetString("Settings_FileTimeoutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Settings_Font {
            get {
                return ResourceManager.GetString("Settings_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size (pt).
        /// </summary>
        public static string Settings_FontSize {
            get {
                return ResourceManager.GetString("Settings_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (seconds) before considering the app frozen..
        /// </summary>
        public static string Settings_ForceQuitDesc {
            get {
                return ResourceManager.GetString("Settings_ForceQuitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Quit Timeout.
        /// </summary>
        public static string Settings_ForceQuitTimeout {
            get {
                return ResourceManager.GetString("Settings_ForceQuitTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Limits.
        /// </summary>
        public static string Settings_Limits {
            get {
                return ResourceManager.GetString("Settings_Limits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent accidental changes. Only Hash Masking remains adjustable..
        /// </summary>
        public static string Settings_LockDesc {
            get {
                return ResourceManager.GetString("Settings_LockDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock as default font.
        /// </summary>
        public static string Settings_LockFont {
            get {
                return ResourceManager.GetString("Settings_LockFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Settings (Save as Default).
        /// </summary>
        public static string Settings_LockSettings {
            get {
                return ResourceManager.GetString("Settings_LockSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock this theme as default.
        /// </summary>
        public static string Settings_LockTheme {
            get {
                return ResourceManager.GetString("Settings_LockTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Hash Values (Security).
        /// </summary>
        public static string Settings_MaskHash {
            get {
                return ResourceManager.GetString("Settings_MaskHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Files per Folder Scan.
        /// </summary>
        public static string Settings_MaxFileCount {
            get {
                return ResourceManager.GetString("Settings_MaxFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the number of files added from a folder to prevent performance issues..
        /// </summary>
        public static string Settings_MaxFileCountDesc {
            get {
                return ResourceManager.GetString("Settings_MaxFileCountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Folders per Click.
        /// </summary>
        public static string Settings_MaxFolderCount {
            get {
                return ResourceManager.GetString("Settings_MaxFolderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the number of folders selected at once..
        /// </summary>
        public static string Settings_MaxFolderCountDesc {
            get {
                return ResourceManager.GetString("Settings_MaxFolderCountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy &amp; Security.
        /// </summary>
        public static string Settings_Other {
            get {
                return ResourceManager.GetString("Settings_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Theme.
        /// </summary>
        public static string Settings_Reset {
            get {
                return ResourceManager.GetString("Settings_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All Settings.
        /// </summary>
        public static string Settings_ResetAll {
            get {
                return ResourceManager.GetString("Settings_ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore to factory defaults..
        /// </summary>
        public static string Settings_ResetDesc {
            get {
                return ResourceManager.GetString("Settings_ResetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Scale.
        /// </summary>
        public static string Settings_Scale {
            get {
                return ResourceManager.GetString("Settings_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Default.
        /// </summary>
        public static string Settings_SetDefault {
            get {
                return ResourceManager.GetString("Settings_SetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Path.
        /// </summary>
        public static string Settings_ShowPath {
            get {
                return ResourceManager.GetString("Settings_ShowPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Read/Write Speed.
        /// </summary>
        public static string Settings_ShowSpeed {
            get {
                return ResourceManager.GetString("Settings_ShowSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display real-time transfer speed during hash operations..
        /// </summary>
        public static string Settings_ShowSpeedDesc {
            get {
                return ResourceManager.GetString("Settings_ShowSpeedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_ThemeDark {
            get {
                return ResourceManager.GetString("Settings_ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_ThemeLight {
            get {
                return ResourceManager.GetString("Settings_ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme style.
        /// </summary>
        public static string Settings_ThemeStyle {
            get {
                return ResourceManager.GetString("Settings_ThemeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Settings_ThemeSystem {
            get {
                return ResourceManager.GetString("Settings_ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light/Dark.
        /// </summary>
        public static string Settings_ThemeVariant {
            get {
                return ResourceManager.GetString("Settings_ThemeVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Status_Cancelled {
            get {
                return ResourceManager.GetString("Status_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update check error: {0}.
        /// </summary>
        public static string Status_CheckError {
            get {
                return ResourceManager.GetString("Status_CheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string Status_Checking {
            get {
                return ResourceManager.GetString("Status_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed!.
        /// </summary>
        public static string Status_Compressed {
            get {
                return ResourceManager.GetString("Status_Compressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash Computing....
        /// </summary>
        public static string Status_Computing {
            get {
                return ResourceManager.GetString("Status_Computing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Status_Done {
            get {
                return ResourceManager.GetString("Status_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash file name mismatch!.
        /// </summary>
        public static string Status_DropHashMismatch {
            get {
                return ResourceManager.GetString("Status_DropHashMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash file dropped successfully.
        /// </summary>
        public static string Status_DropHashSuccess {
            get {
                return ResourceManager.GetString("Status_DropHashSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not contain a hash!.
        /// </summary>
        public static string Status_DropNoHash {
            get {
                return ResourceManager.GetString("Status_DropNoHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string Status_Error {
            get {
                return ResourceManager.GetString("Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash file loaded.
        /// </summary>
        public static string Status_HashFileLoaded {
            get {
                return ResourceManager.GetString("Status_HashFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash file name mismatch!.
        /// </summary>
        public static string Status_HashFileMismatch {
            get {
                return ResourceManager.GetString("Status_HashFileMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation error: {0}.
        /// </summary>
        public static string Status_InstallError {
            get {
                return ResourceManager.GetString("Status_InstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading and installing....
        /// </summary>
        public static string Status_Installing {
            get {
                return ResourceManager.GetString("Status_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISMATCH!.
        /// </summary>
        public static string Status_Invalid {
            get {
                return ResourceManager.GetString("Status_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using the latest version..
        /// </summary>
        public static string Status_Latest {
            get {
                return ResourceManager.GetString("Status_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original file lost!.
        /// </summary>
        public static string Status_LostOriginal {
            get {
                return ResourceManager.GetString("Status_LostOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash value missing (Enter or load hash file).
        /// </summary>
        public static string Status_MissingHash {
            get {
                return ResourceManager.GetString("Status_MissingHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original file missing!.
        /// </summary>
        public static string Status_MissingOriginal {
            get {
                return ResourceManager.GetString("Status_MissingOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version detected!.
        /// </summary>
        public static string Status_NewVersion {
            get {
                return ResourceManager.GetString("Status_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not contain a hash!.
        /// </summary>
        public static string Status_NoHashFound {
            get {
                return ResourceManager.GetString("Status_NoHashFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing ({0})....
        /// </summary>
        public static string Status_Processing {
            get {
                return ResourceManager.GetString("Status_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File read error.
        /// </summary>
        public static string Status_ReadError {
            get {
                return ResourceManager.GetString("Status_ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready (From .hash file).
        /// </summary>
        public static string Status_ReadyFromHash {
            get {
                return ResourceManager.GetString("Status_ReadyFromHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved!.
        /// </summary>
        public static string Status_Saved {
            get {
                return ResourceManager.GetString("Status_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALID.
        /// </summary>
        public static string Status_Valid {
            get {
                return ResourceManager.GetString("Status_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for hash/input....
        /// </summary>
        public static string Status_Waiting {
            get {
                return ResourceManager.GetString("Status_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Hash.
        /// </summary>
        public static string Tip_BrowseHash {
            get {
                return ResourceManager.GetString("Tip_BrowseHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute.
        /// </summary>
        public static string Tip_Compute {
            get {
                return ResourceManager.GetString("Tip_Compute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Hash.
        /// </summary>
        public static string Tip_CopyHash {
            get {
                return ResourceManager.GetString("Tip_CopyHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Path.
        /// </summary>
        public static string Tip_CopyPath {
            get {
                return ResourceManager.GetString("Tip_CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash Visibility.
        /// </summary>
        public static string Tip_HashVisibility {
            get {
                return ResourceManager.GetString("Tip_HashVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Hash.
        /// </summary>
        public static string Tip_HideHash {
            get {
                return ResourceManager.GetString("Tip_HideHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove File.
        /// </summary>
        public static string Tip_RemoveFile {
            get {
                return ResourceManager.GetString("Tip_RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hash.
        /// </summary>
        public static string Tip_ShowHash {
            get {
                return ResourceManager.GetString("Tip_ShowHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Tip_Stop {
            get {
                return ResourceManager.GetString("Tip_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Tip_Verify {
            get {
                return ResourceManager.GetString("Tip_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Title_About {
            get {
                return ResourceManager.GetString("Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Verification.
        /// </summary>
        public static string Title_CheckHash {
            get {
                return ResourceManager.GetString("Title_CheckHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Hash &amp; Compress.
        /// </summary>
        public static string Title_CreateHash {
            get {
                return ResourceManager.GetString("Title_CreateHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Version Warning.
        /// </summary>
        public static string Title_Disclaimer {
            get {
                return ResourceManager.GetString("Title_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string Title_Update {
            get {
                return ResourceManager.GetString("Title_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Unit_Seconds {
            get {
                return ResourceManager.GetString("Unit_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste/Drop here....
        /// </summary>
        public static string Watermark_PasteDrop {
            get {
                return ResourceManager.GetString("Watermark_PasteDrop", resourceCulture);
            }
        }
    }
}
