//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckHash.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CheckHash.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        public static string Menu_Create {
            get {
                return ResourceManager.GetString("Menu_Create", resourceCulture);
            }
        }
        
        public static string Menu_Check {
            get {
                return ResourceManager.GetString("Menu_Check", resourceCulture);
            }
        }
        
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        public static string Menu_Update {
            get {
                return ResourceManager.GetString("Menu_Update", resourceCulture);
            }
        }
        
        public static string Menu_Theme {
            get {
                return ResourceManager.GetString("Menu_Theme", resourceCulture);
            }
        }
        
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        public static string Menu_Developer {
            get {
                return ResourceManager.GetString("Menu_Developer", resourceCulture);
            }
        }
        
        public static string Btn_AddFiles {
            get {
                return ResourceManager.GetString("Btn_AddFiles", resourceCulture);
            }
        }
        
        public static string Btn_Clear {
            get {
                return ResourceManager.GetString("Btn_Clear", resourceCulture);
            }
        }
        
        public static string Btn_CalcAll {
            get {
                return ResourceManager.GetString("Btn_CalcAll", resourceCulture);
            }
        }
        
        public static string Btn_Compress {
            get {
                return ResourceManager.GetString("Btn_Compress", resourceCulture);
            }
        }
        
        public static string Btn_CheckAll {
            get {
                return ResourceManager.GetString("Btn_CheckAll", resourceCulture);
            }
        }
        
        public static string Btn_CheckNow {
            get {
                return ResourceManager.GetString("Btn_CheckNow", resourceCulture);
            }
        }
        
        public static string Btn_Install {
            get {
                return ResourceManager.GetString("Btn_Install", resourceCulture);
            }
        }
        
        public static string Btn_Accept {
            get {
                return ResourceManager.GetString("Btn_Accept", resourceCulture);
            }
        }
        
        public static string Btn_Decline {
            get {
                return ResourceManager.GetString("Btn_Decline", resourceCulture);
            }
        }
        
        public static string Title_CreateHash {
            get {
                return ResourceManager.GetString("Title_CreateHash", resourceCulture);
            }
        }
        
        public static string Title_CheckHash {
            get {
                return ResourceManager.GetString("Title_CheckHash", resourceCulture);
            }
        }
        
        public static string Title_Update {
            get {
                return ResourceManager.GetString("Title_Update", resourceCulture);
            }
        }
        
        public static string Title_Disclaimer {
            get {
                return ResourceManager.GetString("Title_Disclaimer", resourceCulture);
            }
        }
        
        public static string Title_About {
            get {
                return ResourceManager.GetString("Title_About", resourceCulture);
            }
        }
        
        public static string Help_CreateHash {
            get {
                return ResourceManager.GetString("Help_CreateHash", resourceCulture);
            }
        }
        
        public static string Help_CheckHash {
            get {
                return ResourceManager.GetString("Help_CheckHash", resourceCulture);
            }
        }
        
        public static string Lbl_Status_Ready {
            get {
                return ResourceManager.GetString("Lbl_Status_Ready", resourceCulture);
            }
        }
        
        public static string Lbl_Sample {
            get {
                return ResourceManager.GetString("Lbl_Sample", resourceCulture);
            }
        }
        
        public static string Lbl_CurrentVersion {
            get {
                return ResourceManager.GetString("Lbl_CurrentVersion", resourceCulture);
            }
        }
        
        public static string Lbl_Channel {
            get {
                return ResourceManager.GetString("Lbl_Channel", resourceCulture);
            }
        }
        
        public static string Lbl_TotalFiles {
            get {
                return ResourceManager.GetString("Lbl_TotalFiles", resourceCulture);
            }
        }
        
        public static string Channel_Stable {
            get {
                return ResourceManager.GetString("Channel_Stable", resourceCulture);
            }
        }
        
        public static string Channel_Dev {
            get {
                return ResourceManager.GetString("Channel_Dev", resourceCulture);
            }
        }
        
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        public static string Settings_ThemeStyle {
            get {
                return ResourceManager.GetString("Settings_ThemeStyle", resourceCulture);
            }
        }
        
        public static string Settings_ThemeVariant {
            get {
                return ResourceManager.GetString("Settings_ThemeVariant", resourceCulture);
            }
        }
        
        public static string Settings_Font {
            get {
                return ResourceManager.GetString("Settings_Font", resourceCulture);
            }
        }
        
        public static string Settings_FontSize {
            get {
                return ResourceManager.GetString("Settings_FontSize", resourceCulture);
            }
        }
        
        public static string Settings_AutoFont {
            get {
                return ResourceManager.GetString("Settings_AutoFont", resourceCulture);
            }
        }
        
        public static string Settings_LockFont {
            get {
                return ResourceManager.GetString("Settings_LockFont", resourceCulture);
            }
        }
        
        public static string Settings_Scale {
            get {
                return ResourceManager.GetString("Settings_Scale", resourceCulture);
            }
        }
        
        public static string Settings_MaskHash {
            get {
                return ResourceManager.GetString("Settings_MaskHash", resourceCulture);
            }
        }
        
        public static string Settings_Reset {
            get {
                return ResourceManager.GetString("Settings_Reset", resourceCulture);
            }
        }
        
        public static string Settings_Other {
            get {
                return ResourceManager.GetString("Settings_Other", resourceCulture);
            }
        }
        
        public static string Settings_SetDefault {
            get {
                return ResourceManager.GetString("Settings_SetDefault", resourceCulture);
            }
        }
        
        public static string Settings_CustomColor {
            get {
                return ResourceManager.GetString("Settings_CustomColor", resourceCulture);
            }
        }
        
        public static string Settings_Advanced {
            get {
                return ResourceManager.GetString("Settings_Advanced", resourceCulture);
            }
        }
        
        public static string Settings_AdminMode {
            get {
                return ResourceManager.GetString("Settings_AdminMode", resourceCulture);
            }
        }
        
        public static string Settings_AdminDesc {
            get {
                return ResourceManager.GetString("Settings_AdminDesc", resourceCulture);
            }
        }
        
        public static string Settings_FileSizeLimit {
            get {
                return ResourceManager.GetString("Settings_FileSizeLimit", resourceCulture);
            }
        }
        
        public static string Settings_FileSizeDesc {
            get {
                return ResourceManager.GetString("Settings_FileSizeDesc", resourceCulture);
            }
        }
        
        public static string Settings_ForceQuitTimeout {
            get {
                return ResourceManager.GetString("Settings_ForceQuitTimeout", resourceCulture);
            }
        }
        
        public static string Settings_ForceQuitDesc {
            get {
                return ResourceManager.GetString("Settings_ForceQuitDesc", resourceCulture);
            }
        }
        
        public static string Settings_FileTimeout {
            get {
                return ResourceManager.GetString("Settings_FileTimeout", resourceCulture);
            }
        }
        
        public static string Settings_FileTimeoutDesc {
            get {
                return ResourceManager.GetString("Settings_FileTimeoutDesc", resourceCulture);
            }
        }
        
        public static string Settings_Emergency {
            get {
                return ResourceManager.GetString("Settings_Emergency", resourceCulture);
            }
        }
        
        public static string Settings_EmergencyDesc {
            get {
                return ResourceManager.GetString("Settings_EmergencyDesc", resourceCulture);
            }
        }
        
        public static string Settings_BtnForceQuit {
            get {
                return ResourceManager.GetString("Settings_BtnForceQuit", resourceCulture);
            }
        }
        
        public static string Settings_Configuration {
            get {
                return ResourceManager.GetString("Settings_Configuration", resourceCulture);
            }
        }
        
        public static string Settings_LockSettings {
            get {
                return ResourceManager.GetString("Settings_LockSettings", resourceCulture);
            }
        }
        
        public static string Settings_LockDesc {
            get {
                return ResourceManager.GetString("Settings_LockDesc", resourceCulture);
            }
        }
        
        public static string Settings_ResetAll {
            get {
                return ResourceManager.GetString("Settings_ResetAll", resourceCulture);
            }
        }
        
        public static string Settings_ResetDesc {
            get {
                return ResourceManager.GetString("Settings_ResetDesc", resourceCulture);
            }
        }
        
        public static string Settings_ConfigPath {
            get {
                return ResourceManager.GetString("Settings_ConfigPath", resourceCulture);
            }
        }
        
        public static string Settings_ConfigDesc {
            get {
                return ResourceManager.GetString("Settings_ConfigDesc", resourceCulture);
            }
        }
        
        public static string Settings_ShowPath {
            get {
                return ResourceManager.GetString("Settings_ShowPath", resourceCulture);
            }
        }
        
        public static string Settings_AutoSave {
            get {
                return ResourceManager.GetString("Settings_AutoSave", resourceCulture);
            }
        }
        
        public static string Settings_DeveloperMode {
            get {
                return ResourceManager.GetString("Settings_DeveloperMode", resourceCulture);
            }
        }
        
        public static string Settings_DeveloperDesc {
            get {
                return ResourceManager.GetString("Settings_DeveloperDesc", resourceCulture);
            }
        }
        
        public static string Dev_Console {
            get {
                return ResourceManager.GetString("Dev_Console", resourceCulture);
            }
        }
        
        public static string Dev_Beta {
            get {
                return ResourceManager.GetString("Dev_Beta", resourceCulture);
            }
        }
        
        public static string Dev_Recording {
            get {
                return ResourceManager.GetString("Dev_Recording", resourceCulture);
            }
        }
        
        public static string Dev_Paused {
            get {
                return ResourceManager.GetString("Dev_Paused", resourceCulture);
            }
        }
        
        public static string Dev_SaveToFile {
            get {
                return ResourceManager.GetString("Dev_SaveToFile", resourceCulture);
            }
        }
        
        public static string Dev_NoSave {
            get {
                return ResourceManager.GetString("Dev_NoSave", resourceCulture);
            }
        }
        
        public static string Dev_Clear {
            get {
                return ResourceManager.GetString("Dev_Clear", resourceCulture);
            }
        }
        
        public static string Dev_Copy {
            get {
                return ResourceManager.GetString("Dev_Copy", resourceCulture);
            }
        }
        
        public static string Dev_OpenFolder {
            get {
                return ResourceManager.GetString("Dev_OpenFolder", resourceCulture);
            }
        }
        
        public static string About_Author {
            get {
                return ResourceManager.GetString("About_Author", resourceCulture);
            }
        }
        
        public static string About_Software {
            get {
                return ResourceManager.GetString("About_Software", resourceCulture);
            }
        }
        
        public static string About_ThirdParty {
            get {
                return ResourceManager.GetString("About_ThirdParty", resourceCulture);
            }
        }
        
        public static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        public static string About_Desc {
            get {
                return ResourceManager.GetString("About_Desc", resourceCulture);
            }
        }
        
        public static string About_License {
            get {
                return ResourceManager.GetString("About_License", resourceCulture);
            }
        }
        
        public static string About_Tech {
            get {
                return ResourceManager.GetString("About_Tech", resourceCulture);
            }
        }
        
        public static string About_TechContent {
            get {
                return ResourceManager.GetString("About_TechContent", resourceCulture);
            }
        }
        
        public static string About_AI {
            get {
                return ResourceManager.GetString("About_AI", resourceCulture);
            }
        }
        
        public static string About_AIContent {
            get {
                return ResourceManager.GetString("About_AIContent", resourceCulture);
            }
        }
        
        public static string Status_Processing {
            get {
                return ResourceManager.GetString("Status_Processing", resourceCulture);
            }
        }
        
        public static string Status_Done {
            get {
                return ResourceManager.GetString("Status_Done", resourceCulture);
            }
        }
        
        public static string Status_Error {
            get {
                return ResourceManager.GetString("Status_Error", resourceCulture);
            }
        }
        
        public static string Status_Cancelled {
            get {
                return ResourceManager.GetString("Status_Cancelled", resourceCulture);
            }
        }
        
        public static string Status_Saved {
            get {
                return ResourceManager.GetString("Status_Saved", resourceCulture);
            }
        }
        
        public static string Status_Compressed {
            get {
                return ResourceManager.GetString("Status_Compressed", resourceCulture);
            }
        }
        
        public static string Status_Waiting {
            get {
                return ResourceManager.GetString("Status_Waiting", resourceCulture);
            }
        }
        
        public static string Status_MissingOriginal {
            get {
                return ResourceManager.GetString("Status_MissingOriginal", resourceCulture);
            }
        }
        
        public static string Status_MissingHash {
            get {
                return ResourceManager.GetString("Status_MissingHash", resourceCulture);
            }
        }
        
        public static string Status_Valid {
            get {
                return ResourceManager.GetString("Status_Valid", resourceCulture);
            }
        }
        
        public static string Status_Invalid {
            get {
                return ResourceManager.GetString("Status_Invalid", resourceCulture);
            }
        }
        
        public static string Status_HashFileLoaded {
            get {
                return ResourceManager.GetString("Status_HashFileLoaded", resourceCulture);
            }
        }
        
        public static string Status_HashFileMismatch {
            get {
                return ResourceManager.GetString("Status_HashFileMismatch", resourceCulture);
            }
        }
        
        public static string Status_NoHashFound {
            get {
                return ResourceManager.GetString("Status_NoHashFound", resourceCulture);
            }
        }
        
        public static string Status_Checking {
            get {
                return ResourceManager.GetString("Status_Checking", resourceCulture);
            }
        }
        
        public static string Status_NewVersion {
            get {
                return ResourceManager.GetString("Status_NewVersion", resourceCulture);
            }
        }
        
        public static string Status_Latest {
            get {
                return ResourceManager.GetString("Status_Latest", resourceCulture);
            }
        }
        
        public static string Status_CheckError {
            get {
                return ResourceManager.GetString("Status_CheckError", resourceCulture);
            }
        }
        
        public static string Status_Installing {
            get {
                return ResourceManager.GetString("Status_Installing", resourceCulture);
            }
        }
        
        public static string Status_InstallError {
            get {
                return ResourceManager.GetString("Status_InstallError", resourceCulture);
            }
        }
        
        public static string Status_ReadyFromHash {
            get {
                return ResourceManager.GetString("Status_ReadyFromHash", resourceCulture);
            }
        }
        
        public static string Status_LostOriginal {
            get {
                return ResourceManager.GetString("Status_LostOriginal", resourceCulture);
            }
        }
        
        public static string Status_DropHashMismatch {
            get {
                return ResourceManager.GetString("Status_DropHashMismatch", resourceCulture);
            }
        }
        
        public static string Status_DropHashSuccess {
            get {
                return ResourceManager.GetString("Status_DropHashSuccess", resourceCulture);
            }
        }
        
        public static string Status_DropNoHash {
            get {
                return ResourceManager.GetString("Status_DropNoHash", resourceCulture);
            }
        }
        
        public static string Status_ReadError {
            get {
                return ResourceManager.GetString("Status_ReadError", resourceCulture);
            }
        }
        
        public static string Msg_Result_Title {
            get {
                return ResourceManager.GetString("Msg_Result_Title", resourceCulture);
            }
        }
        
        public static string Msg_Result_Content {
            get {
                return ResourceManager.GetString("Msg_Result_Content", resourceCulture);
            }
        }
        
        public static string Msg_CheckResult {
            get {
                return ResourceManager.GetString("Msg_CheckResult", resourceCulture);
            }
        }
        
        public static string Msg_WrongHashFile {
            get {
                return ResourceManager.GetString("Msg_WrongHashFile", resourceCulture);
            }
        }
        
        public static string Msg_WrongHashFileContent {
            get {
                return ResourceManager.GetString("Msg_WrongHashFileContent", resourceCulture);
            }
        }
        
        public static string Msg_UpdateTitle {
            get {
                return ResourceManager.GetString("Msg_UpdateTitle", resourceCulture);
            }
        }
        
        public static string Msg_UpdateContent {
            get {
                return ResourceManager.GetString("Msg_UpdateContent", resourceCulture);
            }
        }
        
        public static string Msg_NoUpdate {
            get {
                return ResourceManager.GetString("Msg_NoUpdate", resourceCulture);
            }
        }
        
        public static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        public static string Msg_ReadHashError {
            get {
                return ResourceManager.GetString("Msg_ReadHashError", resourceCulture);
            }
        }
        
        public static string Msg_ConfigCheck {
            get {
                return ResourceManager.GetString("Msg_ConfigCheck", resourceCulture);
            }
        }
        
        public static string Msg_ConfigExists {
            get {
                return ResourceManager.GetString("Msg_ConfigExists", resourceCulture);
            }
        }
        
        public static string Msg_ConfigMissing {
            get {
                return ResourceManager.GetString("Msg_ConfigMissing", resourceCulture);
            }
        }
        
        public static string Msg_ConfigCreated {
            get {
                return ResourceManager.GetString("Msg_ConfigCreated", resourceCulture);
            }
        }
        
        public static string Msg_ConfigCopied {
            get {
                return ResourceManager.GetString("Msg_ConfigCopied", resourceCulture);
            }
        }
        
        public static string Msg_AdminMode {
            get {
                return ResourceManager.GetString("Msg_AdminMode", resourceCulture);
            }
        }
        
        public static string Msg_AdminRestart {
            get {
                return ResourceManager.GetString("Msg_AdminRestart", resourceCulture);
            }
        }
        
        public static string Msg_OpenFolderError {
            get {
                return ResourceManager.GetString("Msg_OpenFolderError", resourceCulture);
            }
        }
        
        public static string Msg_DisclaimerTitle {
            get {
                return ResourceManager.GetString("Msg_DisclaimerTitle", resourceCulture);
            }
        }
        
        public static string Msg_DisclaimerContent {
            get {
                return ResourceManager.GetString("Msg_DisclaimerContent", resourceCulture);
            }
        }
        
        public static string Msg_DisclaimerAgree {
            get {
                return ResourceManager.GetString("Msg_DisclaimerAgree", resourceCulture);
            }
        }
        
        public static string Dialog_SaveHash {
            get {
                return ResourceManager.GetString("Dialog_SaveHash", resourceCulture);
            }
        }
        
        public static string Dialog_SaveZip {
            get {
                return ResourceManager.GetString("Dialog_SaveZip", resourceCulture);
            }
        }
        
        public static string Dialog_SelectFiles {
            get {
                return ResourceManager.GetString("Dialog_SelectFiles", resourceCulture);
            }
        }
        
        public static string Dialog_SelectHashFile {
            get {
                return ResourceManager.GetString("Dialog_SelectHashFile", resourceCulture);
            }
        }
        
        public static string Dialog_SelectCheckFiles {
            get {
                return ResourceManager.GetString("Dialog_SelectCheckFiles", resourceCulture);
            }
        }
        
        public static string Header_Fallback {
            get {
                return ResourceManager.GetString("Header_Fallback", resourceCulture);
            }
        }
        
        public static string Desc_Fallback {
            get {
                return ResourceManager.GetString("Desc_Fallback", resourceCulture);
            }
        }
        
        public static string Watermark_PasteDrop {
            get {
                return ResourceManager.GetString("Watermark_PasteDrop", resourceCulture);
            }
        }
        
        public static string Unit_Seconds {
            get {
                return ResourceManager.GetString("Unit_Seconds", resourceCulture);
            }
        }
        
        public static string Tip_Verify {
            get {
                return ResourceManager.GetString("Tip_Verify", resourceCulture);
            }
        }
        
        public static string Tip_Stop {
            get {
                return ResourceManager.GetString("Tip_Stop", resourceCulture);
            }
        }
        
        public static string Tip_RemoveFile {
            get {
                return ResourceManager.GetString("Tip_RemoveFile", resourceCulture);
            }
        }
        
        public static string Tip_CopyHash {
            get {
                return ResourceManager.GetString("Tip_CopyHash", resourceCulture);
            }
        }
        
        public static string Tip_Compute {
            get {
                return ResourceManager.GetString("Tip_Compute", resourceCulture);
            }
        }
        
        public static string Tip_BrowseHash {
            get {
                return ResourceManager.GetString("Tip_BrowseHash", resourceCulture);
            }
        }
        
        public static string Settings_ThemeDark {
            get {
                return ResourceManager.GetString("Settings_ThemeDark", resourceCulture);
            }
        }
        
        public static string Settings_ThemeLight {
            get {
                return ResourceManager.GetString("Settings_ThemeLight", resourceCulture);
            }
        }
        
        public static string Settings_ThemeSystem {
            get {
                return ResourceManager.GetString("Settings_ThemeSystem", resourceCulture);
            }
        }
        
        public static string Msg_TaskCancelled_Title {
            get {
                return ResourceManager.GetString("Msg_TaskCancelled_Title", resourceCulture);
            }
        }
        
        public static string Btn_Yes {
            get {
                return ResourceManager.GetString("Btn_Yes", resourceCulture);
            }
        }
        
        public static string Btn_OK {
            get {
                return ResourceManager.GetString("Btn_OK", resourceCulture);
            }
        }
        
        public static string Btn_No {
            get {
                return ResourceManager.GetString("Btn_No", resourceCulture);
            }
        }
        
        public static string Dialog_FileType_Zip {
            get {
                return ResourceManager.GetString("Dialog_FileType_Zip", resourceCulture);
            }
        }
        
        public static string Msg_ConfirmExit_Title {
            get {
                return ResourceManager.GetString("Msg_ConfirmExit_Title", resourceCulture);
            }
        }
        
        public static string Msg_ConfirmExit_Content {
            get {
                return ResourceManager.GetString("Msg_ConfirmExit_Content", resourceCulture);
            }
        }
        
        public static string Msg_TaskCancelled_Content {
            get {
                return ResourceManager.GetString("Msg_TaskCancelled_Content", resourceCulture);
            }
        }
        
        public static string Dev_ToolTip_Save {
            get {
                return ResourceManager.GetString("Dev_ToolTip_Save", resourceCulture);
            }
        }
        
        public static string Dev_ToolTip_Pause {
            get {
                return ResourceManager.GetString("Dev_ToolTip_Pause", resourceCulture);
            }
        }
        
        public static string Tip_ShowHash {
            get {
                return ResourceManager.GetString("Tip_ShowHash", resourceCulture);
            }
        }
        
        public static string Tip_HideHash {
            get {
                return ResourceManager.GetString("Tip_HideHash", resourceCulture);
            }
        }
        
        public static string Tip_CopyPath {
            get {
                return ResourceManager.GetString("Tip_CopyPath", resourceCulture);
            }
        }
        
        public static string Msg_DiskFull {
            get {
                return ResourceManager.GetString("Msg_DiskFull", resourceCulture);
            }
        }
        
        public static string Tip_HashVisibility {
            get {
                return ResourceManager.GetString("Tip_HashVisibility", resourceCulture);
            }
        }
        
        public static string EmptyState_DropFiles {
            get {
                return ResourceManager.GetString("EmptyState_DropFiles", resourceCulture);
            }
        }
        
        public static string Settings_LockTheme {
            get {
                return ResourceManager.GetString("Settings_LockTheme", resourceCulture);
            }
        }
        
        public static string Msg_FileSizeLimitExceeded_Summary {
            get {
                return ResourceManager.GetString("Msg_FileSizeLimitExceeded_Summary", resourceCulture);
            }
        }
        
        public static string Msg_SystemLanguage {
            get {
                return ResourceManager.GetString("Msg_SystemLanguage", resourceCulture);
            }
        }
        
        public static string Msg_SystemLanguageWarning {
            get {
                return ResourceManager.GetString("Msg_SystemLanguageWarning", resourceCulture);
            }
        }
        
        public static string Msg_LanguageChangeTitle {
            get {
                return ResourceManager.GetString("Msg_LanguageChangeTitle", resourceCulture);
            }
        }
        
        public static string Msg_LanguageChangeConfirmation {
            get {
                return ResourceManager.GetString("Msg_LanguageChangeConfirmation", resourceCulture);
            }
        }
        
        public static string Msg_DontShowAgain {
            get {
                return ResourceManager.GetString("Msg_DontShowAgain", resourceCulture);
            }
        }
        
        public static string Error_Network {
            get {
                return ResourceManager.GetString("Error_Network", resourceCulture);
            }
        }
        
        public static string Error_Server {
            get {
                return ResourceManager.GetString("Error_Server", resourceCulture);
            }
        }
        
        public static string Error_Client {
            get {
                return ResourceManager.GetString("Error_Client", resourceCulture);
            }
        }
        
        public static string Error_ApiLimit {
            get {
                return ResourceManager.GetString("Error_ApiLimit", resourceCulture);
            }
        }
        
        public static string Msg_NoPreRelease {
            get {
                return ResourceManager.GetString("Msg_NoPreRelease", resourceCulture);
            }
        }
        
        public static string Msg_PreReleaseWarning {
            get {
                return ResourceManager.GetString("Msg_PreReleaseWarning", resourceCulture);
            }
        }
    }
}
